### ISSUE TITLE
compatibility to www.skytorrents.to

### ISSUE THREAD

**Issue by mzramna** [pedrolemoz/MagicMagnet#18]
www.skytorrents.to
resultados na pagina,
multiplas paginas

**Comment by mzramna** [comment]
https://www.limetorrents.info/
resultado em subpagina,multiplas páginas

**Comment by pedrolemoz** [comment]
I'll add this two soon

**Comment by mzramna** [comment]
i'm working in this already

**Comment by pedrolemoz** [comment]
I've implemented as you can see here: https://github.com/pedrolemoz/MagicMagnet-Python/blob/93e3eea10b9ba43d4e81f8d23702e7f8bef0175a/scripts/algorithm.py#L73
